# Dependencies
markdown: kramdown
highlighter: pygments

permalink: /:title/
url: http://vaveee.github.com
name: vaveee
author: vaveee
qq: 344375148
email: vaveee@qq.com
duoshuo: vaveee
github: vaveee
safe: true
paginate: 20
about: "这里是 李冠南 的个人博客，创建于 2014年10月23号。"
