# Dependencies
markdown: kramdown
rouge: pygments
gems: [jekyll-paginate]
paginate: 15
paginate_path: "page:num"

permalink: /:title/
url: http://vaveee.github.com
name: vaveee
author: vaveee
qq: 344375148
email: vaveee@qq.com
duoshuo: vaveee
github: vaveee
plugins: [jekyll-paginate]
#safe: true
about: "这里是 辣味儿 的个人博客，创建于 2014年10月23号。"

theme: jekyll-theme-cayman